server.port=9090
spring.application.name=api-gateway

# Register with Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Route all requests through Eureka service discovery automatically
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

# Logging
logging.level.org.springframework.cloud.gateway=DEBUG